Clarify usage step
catppuccin/dark-reader pull request #9
Opened 2024-06-30 22:15 UTC by jurdanetac

Explicitly state to open the Dev Tools and go to the Advanced section, that's where the Preview new design option is

2024-06-30 22:54 UTC, uncenter commented on README.md
> +3. Now click on `See all options` → `Colors`.
```suggestion
2. Click on **Dev Tools** > **Advanced** > **Preview new design** and close the window.
3. Now click on **See all options** > **Colors**.
```

2024-07-05 14:11 UTC, moiSentineL approved these changes
thanks!

2024-08-28 10:50 UTC, sgoudham requested changes
Hey, thanks for the PR!

You'll need to edit the following lines here since the README is generated via [catppuccin/whiskers](https://github.com/catppuccin/whiskers) from this file:
https://github.com/catppuccin/dark-reader/blob/560b302f12d402bd9966d177a023c0659c674a68/dark-reader.tera#L28-L30

2024-08-30 06:41 UTC, sgoudham commented
Superceded by #10

2024-08-30 06:41 UTC, closed without merging